# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Containerize
on:
  pull_request:
    branches: # Specify your branches here
      - develop
  push:
    branches:
      - develop
  release:
    types: [created]

jobs:
  build-publish-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project:
          - envoy-java-ctlp
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Check Format, Style
        run: ./gradlew :checkFormat :checkStyleMain :checkStyleTest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish container  ${{ matrix.project }}
        run: ./gradlew :jib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
